on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "15 4 * * 0" # Every Sunday morning

name: bash

jobs:
  shellcheck:
    name: Test Bash Scripts
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.30 # we need prove
    steps:
      - uses: actions/checkout@master
      - name: install Bats
        run: >
          cd /tmp &&
          git clone https://github.com/bats-core/bats-core.git --depth 1 &&
          cd bats-core &&
          ./install.sh /usr/local
      - name: Install Minilla
        run: cpm install -g Minilla
      - name: Configure git
        run: >
          git config --global user.email "foo@example.com" &&
          git config --global user.name "Min Illa"
      - name: Running tests
        run: bats -t t/dzil_module.bats t/minil_module.bats
